### ISSUE TITLE
Composer Update doesn't recognize existing stubs

### ISSUE THREAD

**Issue by maddeezy** [bpocallaghan/generators#11]
Hey Ben-Piet!

It's been awhile, I saw the update so I ran it...

However, if stubs are already published, they need to be published again with --force in order for them to be used...I just cleaned in git all my existing stubs, then it worked...

**Comment by bpocallaghan** [comment]
Hi Erik

Yeah, sorry, been a bit busy with other stuff - still need to find some time for those other 2 updates.

Jap, I did some updates to the  [Laravel Admin Starter](https://github.com/bpocallaghan/laravel-admin-starter) and then did some minor stuff on the controller stub in this package.
Not really sure about this one thing. Have a look at the [Controller Stub](https://github.com/bpocallaghan/generators/blob/master/resources/stubs/controller.stub)

I've added a global helper function `save_resource_url();` so that I can do `return redirect_to_resource();`
The latest project I had a menu like /admin/foo and also /backoffice/foo - so its different redirect links. Then I save the 'home resource' in session and redirect back to it.

I kinda liked it coz then you do not have to edit the 'return' url in the controller...
But not all will have that helper function - so not sure if I should rather take it out and leave as what it was? Thoughts?

Cool. I am not sure if you will be able to hook up into the 'projects composer' after an update.
I think that all depends how the projects 'composer.json' is setup? 
But will be nice to show a 'hint / note' - We see you've updated the generators - would you like to export the stubs again, but then again, you only export the stubs when you want to replace it with your own - so you might not want to override your existing ones. hehe - maybe I am confused :)

**Comment by bpocallaghan** [comment]
Hi Erik

Sorry for the long wait. I misunderstood you the first time, but think I am slightly confused.

If I am correct you mean.
You've published the config + stubs.
Then you've updated to the latest version.
Then when you generate a file - it took the stub from the package instead of the published ones (resources/stubs)?

I just ran the command to copy the config + stubs and then I updated the package to latest version.
When I generate a file - it did use the /resources/stubs file and not the package's?

I just want to make sure. Maybe you deleted the config/generators.php or the /resource/stubs folder?
Or do I imagine it that it was always /resources/views/stubs but now its /resources/stubs ? Why it did not find the config + stubs in project and used the package's stubs?

Sorry, or maybe I am confused?

**Comment by maddeezy** [comment]
I'll check to make sure my generators.php file was/is not missing, but yeah, what you described is what was happening to me after update...

As for the save_redirect_url(), that seems like it will be helpful.  I have an issue where we are using a single page application and reload the #contents div...we added a "back" button and load that with a variable from the controller...maybe this might save us from having to do that...
