### ISSUE TITLE
Enhancement for repositories/contracts

### ISSUE THREAD

**Issue by maddeezy** [bpocallaghan/generators#14]
Would it be possible to also add stubs for repositories and contracts?

Our project is growing and it would be nice to stub out this when we use generate:resource foo and maybe add flags to include a repository and contract?

What do you think?

We also came across the quasar framework

Totally Vue..pretty nice...thought I would share.

http://quasar-framework.org

**Comment by bpocallaghan** [comment]
Hi @maddeezy 

Thanks for the link - yeah I really want to get into vuejs, but all in due time I guess ;)

For sure. I was actually planning on adding jobs and console commands over the weekend.
I will also look at contracts and repositories - I will let you know once I've added them - coz I think I might be missing something as I hardly use them, maybe you can give me some pointers to finalize it (but let me first create those 2 commands and then we chat about it.

Thanks.

**Comment by bpocallaghan** [comment]
Hi @maddeezy 
Latest version 4.1.7.
I've added the [Repository](https://github.com/bpocallaghan/generators/blob/master/readme.md#repository) and [Contract](https://github.com/bpocallaghan/generators/blob/master/readme.md#contract) commands.

If you want - please send me an example of your contract / repository to update the default stubs or controller file. So that when you generate a resource and it asks for a repository - I can use that 'controller_repository.stub' instead of the normal one.

For now they are just standalone commands to call separately. I personally don't use them so I don't know what the 'latest / best' is - please let me know to make it 'easier' for you :)

Thanks

**Comment by maddeezy** [comment]
I'll send to you...where should I send?

It would be nice to use something like:

php artisan generate:resource foobars --controller --repository --contract

Then we get a lot of automation.

**Comment by bpocallaghan** [comment]
Please email it to bpocallaghan @ gmail

Yes, I was actually thinking to make it a 'question' - just before the controller gets generated (for the correct stub) So the repository injection is in the controller stub - but I will have a look at ur example.

**Comment by bpocallaghan** [comment]
Version 4.1.8
