### ISSUE TITLE
AdminController which all controller extend is not exist already !

### ISSUE THREAD

**Issue by abdelrahmanbadr** [bpocallaghan/generators#16]

**Comment by bpocallaghan** [comment]
Hi @abdelrahmanbadr 
Thank you for giving this package a try.
If you are talking about this [stub](https://github.com/bpocallaghan/generators/blob/master/resources/stubs/controller.stub)
You are correct - The default stub is extending the `AdminController` as its mostly used for CRUD in the admin.

I do understand that it can frustrate you.
If you want you can have a look at this [starter project](https://github.com/bpocallaghan/laravel-admin-starter) to see why I have it extending the `AdminController`.
However I can imagine it not working for you.

May I suggest.

- You can either [publish all the stubs](https://github.com/bpocallaghan/generators#configuration) and add your own boilerplate.
- I will have a look and see if I can perhaps make the default stub more generic so that it does not rely on any other base classes.

Sorry if this caused you more trouble than it should.
The package is supposed to help you :)

**Comment by abdelrahmanbadr** [comment]
Thanks , but please assume that someone will install this package and will not install starter project

**Comment by bpocallaghan** [comment]
Hi @abdelrahmanbadr 
Sorry for the long wait.
The new release (v5.0.2) should be better for you.
I've added a new stub.
`controller, controller_plain, controller_admin`
php artisan generate:controller : will use the `controller` stub
php artisan generate:controller --plain : will use the `controller_plain` stub
php artisan generate:resource : will use the `controller` stub
php artisan generate:resource admin.* : will use the `controller_admin` stub (the one extending AdminController, so if you prefix admin.)

Maybe not 100%, for you but felt like that should be oky for now - as you can always publish the stubs to add your own boilerplate :)

Please shout if you have a better or any other ideas.

Thank you - Happy Coding
